-- Paste these entries inside ox_inventory/data/items.lua
-- (inside the existing `return { ... }` table, before the closing `}`).
-- Image paths are inlined. Do not use img().

return {
    ['fishing_rod_basic'] = {
        label = 'Canal Rod',
        weight = 1200,
        stack = false,
        close = true,
        consume = 0,
        description = 'A Vice City canal stick. Gets you started on the seawall.',
        client = {
            export = 'djfivem-fishing.useRod',
            image = 'nui://djfivem-fishing/images/fishing_rod_basic.png',
        },
    },
    ['fishing_rod_pro'] = {
        label = 'Biscayne Rod',
        weight = 1100,
        stack = false,
        close = true,
        consume = 0,
        description = 'Carbon blank for the bay. Better luck on snook and mahi.',
        client = {
            export = 'djfivem-fishing.useRod',
            image = 'nui://djfivem-fishing/images/fishing_rod_pro.png',
        },
    },
    ['fishing_rod_elite'] = {
        label = 'Gulf Stream Rod',
        weight = 1400,
        stack = false,
        close = true,
        consume = 0,
        description = 'Heavy-action rod for tarpon and shark.',
        client = {
            export = 'djfivem-fishing.useRod',
            image = 'nui://djfivem-fishing/images/fishing_rod_elite.png',
        },
    },
    ['fishing_rod_miami'] = {
        label = 'Neon 305 Rod',
        weight = 1350,
        stack = false,
        close = true,
        consume = 0,
        description = 'Signature 305 blank. Built for silver kings after dark.',
        client = {
            export = 'djfivem-fishing.useRod',
            image = 'nui://djfivem-fishing/images/fishing_rod_miami.png',
        },
    },
    ['fishing_reel_basic'] = {
        label = 'South Beach Spin',
        weight = 450,
        stack = false,
        close = true,
        consume = 0,
        description = 'Reliable spinning reel.',
        client = { image = 'nui://djfivem-fishing/images/fishing_reel_basic.png' },
    },
    ['fishing_reel_pro'] = {
        label = 'Calle Ocho Caster',
        weight = 500,
        stack = false,
        close = true,
        consume = 0,
        description = 'Smoother drag for tougher fish.',
        client = { image = 'nui://djfivem-fishing/images/fishing_reel_pro.png' },
    },
    ['fishing_reel_elite'] = {
        label = 'Midnight Reel',
        weight = 560,
        stack = false,
        close = true,
        consume = 0,
        description = 'Saltwater drag system.',
        client = { image = 'nui://djfivem-fishing/images/fishing_reel_elite.png' },
    },
    ['fishing_line'] = {
        label = 'Fluoro Line',
        weight = 20,
        stack = true,
        close = false,
        consume = 0,
        description = 'Clear fluoro. Each spool lasts 20 bites.',
        client = { image = 'nui://djfivem-fishing/images/fishing_line.png' },
    },
    ['fishing_line_braid'] = {
        label = '305 Braid',
        weight = 18,
        stack = true,
        close = false,
        consume = 0,
        description = 'Pink braid for the night bite. 40 bites a spool.',
        client = { image = 'nui://djfivem-fishing/images/fishing_line_braid.png' },
    },
    ['bait_ocean'] = {
        label = 'Cut Bait',
        weight = 30,
        stack = true,
        close = false,
        description = 'Oily chunks. Works the ocean and Biscayne.',
        client = { image = 'nui://djfivem-fishing/images/bait_ocean.png' },
    },
    ['bait_shrimp'] = {
        label = 'Live Shrimp',
        weight = 28,
        stack = true,
        close = false,
        description = 'Premium 305 bait. Used first on the ocean if you have it.',
        client = { image = 'nui://djfivem-fishing/images/bait_shrimp.png' },
    },
    ['bait_lake'] = {
        label = 'Panfish Bait',
        weight = 25,
        stack = true,
        close = false,
        description = 'Required on lakes and canals.',
        client = { image = 'nui://djfivem-fishing/images/bait_lake.png' },
    },
    ['bait_river'] = {
        label = 'Creek Bait',
        weight = 25,
        stack = true,
        close = false,
        description = 'Required on creeks.',
        client = { image = 'nui://djfivem-fishing/images/bait_river.png' },
    },

    ['fish_sardine'] = {
        label = 'Sardine',
        weight = 200,
        stack = true,
        close = false,
        description = 'Ocean catch.',
        client = { image = 'nui://djfivem-fishing/images/fish_sardine.png' },
    },
    ['fish_rockfish'] = {
        label = 'Rockfish',
        weight = 350,
        stack = true,
        close = false,
        description = 'Ocean catch.',
        client = { image = 'nui://djfivem-fishing/images/fish_rockfish.png' },
    },
    ['fish_tuna'] = {
        label = 'Tuna',
        weight = 700,
        stack = true,
        close = false,
        description = 'Ocean catch.',
        client = { image = 'nui://djfivem-fishing/images/fish_tuna.png' },
    },
    ['fish_marlin'] = {
        label = 'Marlin',
        weight = 1200,
        stack = true,
        close = false,
        description = 'Ocean catch.',
        client = { image = 'nui://djfivem-fishing/images/fish_marlin.png' },
    },
    ['fish_shark'] = {
        label = 'Shark',
        weight = 1600,
        stack = true,
        close = false,
        description = 'Ocean catch.',
        client = { image = 'nui://djfivem-fishing/images/fish_shark.png' },
    },
    ['fish_snapper'] = {
        label = 'Mangrove Snapper',
        weight = 320,
        stack = true,
        close = false,
        description = 'Ocean catch. Hangs on seawalls and pilings.',
        client = { image = 'nui://djfivem-fishing/images/fish_snapper.png' },
    },
    ['fish_snook'] = {
        label = 'Snook',
        weight = 520,
        stack = true,
        close = false,
        description = 'Ocean catch. Linesider under the lights.',
        client = { image = 'nui://djfivem-fishing/images/fish_snook.png' },
    },
    ['fish_permit'] = {
        label = 'Permit',
        weight = 480,
        stack = true,
        close = false,
        description = 'Ocean catch. Spooky flats fish.',
        client = { image = 'nui://djfivem-fishing/images/fish_permit.png' },
    },
    ['fish_bonefish'] = {
        label = 'Bonefish',
        weight = 420,
        stack = true,
        close = false,
        description = 'Ocean catch. Grey ghost of the flats.',
        client = { image = 'nui://djfivem-fishing/images/fish_bonefish.png' },
    },
    ['fish_mahi'] = {
        label = 'Mahi-Mahi',
        weight = 750,
        stack = true,
        close = false,
        description = 'Ocean catch. Gulf Stream gold.',
        client = { image = 'nui://djfivem-fishing/images/fish_mahi.png' },
    },
    ['fish_tarpon'] = {
        label = 'Silver King',
        weight = 1700,
        stack = true,
        close = false,
        description = 'Ocean catch. The 305 trophy.',
        client = { image = 'nui://djfivem-fishing/images/fish_tarpon.png' },
    },

    ['fish_bluegill'] = {
        label = 'Bluegill',
        weight = 180,
        stack = true,
        close = false,
        description = 'Lake catch.',
        client = { image = 'nui://djfivem-fishing/images/fish_bluegill.png' },
    },
    ['fish_perch'] = {
        label = 'Perch',
        weight = 220,
        stack = true,
        close = false,
        description = 'Lake catch.',
        client = { image = 'nui://djfivem-fishing/images/fish_perch.png' },
    },
    ['fish_smallmouth_bass'] = {
        label = 'Smallmouth Bass',
        weight = 400,
        stack = true,
        close = false,
        description = 'Lake catch.',
        client = { image = 'nui://djfivem-fishing/images/fish_smallmouth_bass.png' },
    },
    ['fish_largemouth_bass'] = {
        label = 'Largemouth Bass',
        weight = 450,
        stack = true,
        close = false,
        description = 'Lake catch.',
        client = { image = 'nui://djfivem-fishing/images/fish_largemouth_bass.png' },
    },
    ['fish_trout'] = {
        label = 'Trout',
        weight = 380,
        stack = true,
        close = false,
        description = 'Lake catch.',
        client = { image = 'nui://djfivem-fishing/images/fish_trout.png' },
    },
    ['fish_catfish'] = {
        label = 'Catfish',
        weight = 600,
        stack = true,
        close = false,
        description = 'Lake catch.',
        client = { image = 'nui://djfivem-fishing/images/fish_catfish.png' },
    },
    ['fish_tilapia'] = {
        label = 'Tilapia',
        weight = 200,
        stack = true,
        close = false,
        description = 'Lake catch. Warm-water panfish in the canals.',
        client = { image = 'nui://djfivem-fishing/images/fish_tilapia.png' },
    },
    ['fish_peacock_bass'] = {
        label = 'Peacock Bass',
        weight = 500,
        stack = true,
        close = false,
        description = 'Lake catch. Miami canal celebrity.',
        client = { image = 'nui://djfivem-fishing/images/fish_peacock_bass.png' },
    },

    ['fish_salmon'] = {
        label = 'Salmon',
        weight = 500,
        stack = true,
        close = false,
        description = 'River catch.',
        client = { image = 'nui://djfivem-fishing/images/fish_salmon.png' },
    },
    ['fish_striper'] = {
        label = 'Striper',
        weight = 550,
        stack = true,
        close = false,
        description = 'River catch.',
        client = { image = 'nui://djfivem-fishing/images/fish_striper.png' },
    },
}
