-- Paste these entries inside ox_inventory/data/items.lua
-- (inside the existing `return { ... }` table, before the closing `}`).
-- Image paths are inlined. Do not use img().

return {
    ['fishing_rod_basic'] = {
        label = 'Driftwood Rod',
        weight = 1200,
        stack = false,
        close = true,
        consume = 0,
        description = 'A shoreline rod that will get you started.',
        client = {
            export = 'djfivem-fishing.useRod',
            image = 'nui://djfivem-fishing/images/fishing_rod_basic.png',
        },
    },
    ['fishing_rod_pro'] = {
        label = 'Carbon Rod',
        weight = 1100,
        stack = false,
        close = true,
        consume = 0,
        description = 'Lighter blank with better hook-sets.',
        client = {
            export = 'djfivem-fishing.useRod',
            image = 'nui://djfivem-fishing/images/fishing_rod_pro.png',
        },
    },
    ['fishing_rod_elite'] = {
        label = 'Offshore Rod',
        weight = 1400,
        stack = false,
        close = true,
        consume = 0,
        description = 'Heavy-action rod built for marlin and shark.',
        client = {
            export = 'djfivem-fishing.useRod',
            image = 'nui://djfivem-fishing/images/fishing_rod_elite.png',
        },
    },
    ['fishing_reel_basic'] = {
        label = 'Spin Reel',
        weight = 450,
        stack = false,
        close = true,
        consume = 0,
        description = 'Reliable spinning reel.',
        client = { image = 'nui://djfivem-fishing/images/fishing_reel_basic.png' },
    },
    ['fishing_reel_pro'] = {
        label = 'Baitcaster',
        weight = 500,
        stack = false,
        close = true,
        consume = 0,
        description = 'Smoother drag for tougher fish.',
        client = { image = 'nui://djfivem-fishing/images/fishing_reel_pro.png' },
    },
    ['fishing_reel_elite'] = {
        label = 'Tournament Reel',
        weight = 560,
        stack = false,
        close = true,
        consume = 0,
        description = 'Saltwater drag system.',
        client = { image = 'nui://djfivem-fishing/images/fishing_reel_elite.png' },
    },
    ['fishing_line'] = {
        label = 'Fishing Line',
        weight = 20,
        stack = true,
        close = false,
        consume = 0,
        description = 'Mono spool. Each spool lasts 5 bites.',
        client = { image = 'nui://djfivem-fishing/images/fishing_line.png' },
    },
    ['bait_ocean'] = {
        label = 'Ocean Bait',
        weight = 30,
        stack = true,
        close = false,
        description = 'Required to fish the ocean.',
        client = { image = 'nui://djfivem-fishing/images/bait_ocean.png' },
    },
    ['bait_lake'] = {
        label = 'Lake Bait',
        weight = 25,
        stack = true,
        close = false,
        description = 'Required to fish lakes.',
        client = { image = 'nui://djfivem-fishing/images/bait_lake.png' },
    },
    ['bait_river'] = {
        label = 'River Bait',
        weight = 25,
        stack = true,
        close = false,
        description = 'Required to fish rivers.',
        client = { image = 'nui://djfivem-fishing/images/bait_river.png' },
    },

    ['fish_sardine'] = {
        label = 'Sardine',
        weight = 200,
        stack = true,
        close = false,
        description = 'Ocean catch.',
        client = { image = 'nui://djfivem-fishing/images/fish_sardine.png' },
    },
    ['fish_rockfish'] = {
        label = 'Rockfish',
        weight = 350,
        stack = true,
        close = false,
        description = 'Ocean catch.',
        client = { image = 'nui://djfivem-fishing/images/fish_rockfish.png' },
    },
    ['fish_tuna'] = {
        label = 'Tuna',
        weight = 700,
        stack = true,
        close = false,
        description = 'Ocean catch.',
        client = { image = 'nui://djfivem-fishing/images/fish_tuna.png' },
    },
    ['fish_marlin'] = {
        label = 'Marlin',
        weight = 1200,
        stack = true,
        close = false,
        description = 'Ocean catch.',
        client = { image = 'nui://djfivem-fishing/images/fish_marlin.png' },
    },
    ['fish_shark'] = {
        label = 'Shark',
        weight = 1600,
        stack = true,
        close = false,
        description = 'Ocean catch.',
        client = { image = 'nui://djfivem-fishing/images/fish_shark.png' },
    },

    ['fish_bluegill'] = {
        label = 'Bluegill',
        weight = 180,
        stack = true,
        close = false,
        description = 'Lake catch.',
        client = { image = 'nui://djfivem-fishing/images/fish_bluegill.png' },
    },
    ['fish_perch'] = {
        label = 'Perch',
        weight = 220,
        stack = true,
        close = false,
        description = 'Lake catch.',
        client = { image = 'nui://djfivem-fishing/images/fish_perch.png' },
    },
    ['fish_smallmouth_bass'] = {
        label = 'Smallmouth Bass',
        weight = 400,
        stack = true,
        close = false,
        description = 'Lake catch.',
        client = { image = 'nui://djfivem-fishing/images/fish_smallmouth_bass.png' },
    },
    ['fish_largemouth_bass'] = {
        label = 'Largemouth Bass',
        weight = 450,
        stack = true,
        close = false,
        description = 'Lake catch.',
        client = { image = 'nui://djfivem-fishing/images/fish_largemouth_bass.png' },
    },
    ['fish_trout'] = {
        label = 'Trout',
        weight = 380,
        stack = true,
        close = false,
        description = 'Lake catch.',
        client = { image = 'nui://djfivem-fishing/images/fish_trout.png' },
    },
    ['fish_catfish'] = {
        label = 'Catfish',
        weight = 600,
        stack = true,
        close = false,
        description = 'Lake catch.',
        client = { image = 'nui://djfivem-fishing/images/fish_catfish.png' },
    },

    ['fish_salmon'] = {
        label = 'Salmon',
        weight = 500,
        stack = true,
        close = false,
        description = 'River catch.',
        client = { image = 'nui://djfivem-fishing/images/fish_salmon.png' },
    },
    ['fish_striper'] = {
        label = 'Striper',
        weight = 550,
        stack = true,
        close = false,
        description = 'River catch.',
        client = { image = 'nui://djfivem-fishing/images/fish_striper.png' },
    },
}
