-- Copy these entries into ox_inventory/data/items.lua
-- Place matching PNG files in ox_inventory/web/images/ (optional; inventory will show a fallback if missing)

return {
    ['fishing_rod_basic'] = {
        label = 'Driftwood Rod',
        weight = 1200,
        stack = false,
        close = true,
        consume = 0,
        description = 'A shoreline rod that will get you started.',
        client = { export = 'djfivem-fishing.useRod' },
    },
    ['fishing_rod_pro'] = {
        label = 'Carbon Rod',
        weight = 1100,
        stack = false,
        close = true,
        consume = 0,
        description = 'Lighter blank with better hook-sets.',
        client = { export = 'djfivem-fishing.useRod' },
    },
    ['fishing_rod_elite'] = {
        label = 'Offshore Rod',
        weight = 1400,
        stack = false,
        close = true,
        consume = 0,
        description = 'Heavy-action rod built for marlin and shark.',
        client = { export = 'djfivem-fishing.useRod' },
    },
    ['fishing_reel_basic'] = {
        label = 'Spin Reel',
        weight = 450,
        stack = false,
        close = true,
        consume = 0,
        description = 'Reliable spinning reel.',
    },
    ['fishing_reel_pro'] = {
        label = 'Baitcaster',
        weight = 500,
        stack = false,
        close = true,
        consume = 0,
        description = 'Smoother drag for tougher fish.',
    },
    ['fishing_reel_elite'] = {
        label = 'Tournament Reel',
        weight = 560,
        stack = false,
        close = true,
        consume = 0,
        description = 'Saltwater drag system.',
    },
    ['fishing_line'] = {
        label = 'Fishing Line',
        weight = 20,
        stack = true,
        close = false,
        description = 'Mono line. Used each time a fish hits.',
    },
    ['bait_ocean'] = {
        label = 'Ocean Bait',
        weight = 30,
        stack = true,
        close = false,
        description = 'Required to fish the ocean.',
    },
    ['bait_lake'] = {
        label = 'Lake Bait',
        weight = 25,
        stack = true,
        close = false,
        description = 'Required to fish lakes.',
    },
    ['bait_river'] = {
        label = 'River Bait',
        weight = 25,
        stack = true,
        close = false,
        description = 'Required to fish rivers.',
    },

    ['fish_sardine'] = { label = 'Sardine', weight = 200, stack = true, close = false, description = 'Ocean catch.' },
    ['fish_rockfish'] = { label = 'Rockfish', weight = 350, stack = true, close = false, description = 'Ocean catch.' },
    ['fish_tuna'] = { label = 'Tuna', weight = 700, stack = true, close = false, description = 'Ocean catch.' },
    ['fish_marlin'] = { label = 'Marlin', weight = 1200, stack = true, close = false, description = 'Ocean catch.' },
    ['fish_shark'] = { label = 'Shark', weight = 1600, stack = true, close = false, description = 'Ocean catch.' },

    ['fish_bluegill'] = { label = 'Bluegill', weight = 180, stack = true, close = false, description = 'Lake catch.' },
    ['fish_perch'] = { label = 'Perch', weight = 220, stack = true, close = false, description = 'Lake catch.' },
    ['fish_smallmouth_bass'] = { label = 'Smallmouth Bass', weight = 400, stack = true, close = false, description = 'Lake catch.' },
    ['fish_largemouth_bass'] = { label = 'Largemouth Bass', weight = 450, stack = true, close = false, description = 'Lake catch.' },
    ['fish_trout'] = { label = 'Trout', weight = 380, stack = true, close = false, description = 'Lake catch.' },
    ['fish_catfish'] = { label = 'Catfish', weight = 600, stack = true, close = false, description = 'Lake catch.' },

    ['fish_salmon'] = { label = 'Salmon', weight = 500, stack = true, close = false, description = 'River catch.' },
    ['fish_striper'] = { label = 'Striper', weight = 550, stack = true, close = false, description = 'River catch.' },
}
